import {
  codeo,
  erai,
  game,
  idc,
  meta,
  modal,
  movie,
  question,
  quotes,
  shopify,
  starbucks,
  stopwatch,
  tesla,
  todolist,
  watch,
  weather,
} from "../assets/images";
import {
  car,
  contact,
  css,
  estate,
  express,
  git,
  github,
  html,
  javascript,
  linkedin,
  motion,
  mui,
  pricewise,
  react,
  snapgram,
  summiz,
  tailwindcss,
  threads,
  typescript,
  blender,
  mysql,
  chakraui,
} from "../assets/icons";

export const skills = [
  {
    imageUrl: css,
    name: "CSS",
    type: "Frontend",
  },
  {
    imageUrl: git,
    name: "Git",
    type: "Version Control",
  },
  {
    imageUrl: github,
    name: "GitHub",
    type: "Version Control",
  },
  {
    imageUrl: html,
    name: "HTML",
    type: "Frontend",
  },
  {
    imageUrl: javascript,
    name: "JavaScript",
    type: "Frontend",
  },
  {
    imageUrl: mysql,
    name: "MySQL",
    type: "Database",
  },
  {
    imageUrl: motion,
    name: "Motion",
    type: "Animation",
  },
  {
    imageUrl: mui,
    name: "Material-UI",
    type: "Frontend",
  },
  {
    imageUrl: react,
    name: "React",
    type: "Frontend",
  },
  {
    imageUrl: tailwindcss,
    name: "Tailwind CSS",
    type: "Frontend",
  },
  {
    imageUrl: typescript,
    name: "TypeScript",
    type: "Frontend",
  },
  {
    imageUrl: chakraui,
    name: "ChakraUI",
    type: "Frontend",
  },
  {
    imageUrl: blender,
    name: "Blender",
    type: "3D",
  },
];

export const experiences = [
  {
    title: "Java Developer Intern",
    company_name: "Codeograph Solutions",
    icon: codeo,
    iconBg: "#ced4da",
    date: "Aug 2021 - Feb 2022",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Frontend Developer",
    company_name: "iDigiCloud Technologies",
    icon: idc,
    iconBg: "#21295c",
    date: "Mar 2022 - Jul 2023",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
  {
    title: "Bilingual Frontend Developer",
    company_name: "Erai Technologies",
    icon: erai,
    iconBg: "#ced4da",
    date: "Nov 2023 - Present",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },
];

export const socialLinks = [
  {
    name: "Contact",
    iconUrl: contact,
    link: "/contact",
  },
  {
    name: "GitHub",
    iconUrl: github,
    link: "https://github.com/YourGitHubUsername",
  },
  {
    name: "LinkedIn",
    iconUrl: linkedin,
    link: "https://www.linkedin.com/in/YourLinkedInUsername",
  },
];

export const projects = [
  {
    name: "Where is Modal",
    image: modal,
    description: "JavaScript - Where is Modal",
    link: "https://github.com/adrianhajdin/threads",
    hash1: "html",
    hash2: "css",
    hash3: "javascript",
  },
  {
    name: "Frequently Asked Questions",
    image: question,
    description: "JavaScript - Frequently Asked Questions",
    link: "https://github.com/adrianhajdin/project_next13_car_showcase",
    hash1: "html",
    hash2: "css",
    hash3: "javascript",
  },
  {
    name: "Quotes Generator",
    image: quotes,
    description: "JavaScript - Quotes Generator",
    link: "https://github.com/adrianhajdin/social_media_app",
    hash1: "html",
    hash2: "css",
    hash3: "javascript",
  },
  {
    name: "Stop-Watch",
    image: stopwatch,
    description: "JavaScript - Stop Watch",
    link: "https://github.com/adrianhajdin/projects_realestate",
    hash1: "html",
    hash2: "css",
    hash3: "javascript",
  },
  {
    name: "To Do List",
    image: todolist,
    description: "JavaScript - To Do List",
    link: "https://github.com/adrianhajdin/project_ai_summarizer",
    hash1: "html",
    hash2: "css",
    hash3: "javascript",
  },
  {
    name: "Tic Tac Toe",
    image: game,
    description: "JavaScript - Tic Tac Toe",
    link: "https://github.com/adrianhajdin/pricewise",
    hash1: "html",
    hash2: "css",
    hash3: "javascript",
  },
  {
    name: "Analog Watch",
    image: watch,
    description: "JavaScript - Analog Watch",
    link: "https://github.com/adrianhajdin/pricewise",
    hash1: "html",
    hash2: "css",
    hash3: "javascript",
  },
  {
    name: "Weather App",
    image: weather,
    description: "React - Weather App",
    link: "https://github.com/adrianhajdin/pricewise",
    hash1: "html",
    hash2: "css",
    hash3: "React",
  },
  {
    name: "Movie Land",
    image: movie,
    description: "React - Movie Search App",
    link: "https://github.com/adrianhajdin/pricewise",
    hash1: "html",
    hash2: "css",
    hash3: "React",
  },
];
